bundler_args: --without coverage development pcap
cache: bundler
env:
  - RAKE_TASKS="cucumber cucumber:boot"
  - RAKE_TASKS=spec SPEC_OPTS="--tag content"
  - RAKE_TASKS=spec SPEC_OPTS="--tag ~content"

language: ruby
matrix:
  fast_finish: true
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - rake --version
  # Uncomment when we have fewer shipping msftidy warnings.
  # Merge committers will still be checking, just not autofailing.
  # - ln -sf ../../tools/dev/pre-commit-hook.rb ./.git/hooks/post-merge
  # - ls -la ./.git/hooks
  # - ./.git/hooks/post-merge
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake --version
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  # fail build if db/schema.rb update is not committed
  - git diff --exit-code && bundle exec rake $RAKE_TASKS
sudo: false
rvm:
  - '1.9.3'
  - '2.1'

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 5

# Blacklist certain branches from triggering travis builds
branches:
  except:
    - gh-pages
    - metakitty
