language: ruby
before_install:
  - rake --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
before_script:
  - ls -la ./.git/hooks
  - ln -sf ../../tools/dev/pre-commit-hook.rb ./.git/hooks/post-merge
  - ./.git/hooks/post-merge
  - ls -la ./.git/hooks
  - ./tools/msftidy.rb
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake --version
  - bundle exec rake db:create
  - bundle exec rake db:migrate

rvm:
  #- '1.8.7'
  - '1.9.3'

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 5
