sudo: false
group: stable
bundler_args: --without coverage development pcap
cache: bundler
addons:
  postgresql: '9.3'
  apt:
    packages:
      - libpcap-dev
      - graphviz
language: ruby
rvm:
  - '2.3.1'

env:
  - RAKE_TASKS="cucumber cucumber:boot" CREATE_BINSTUBS=true
  - RAKE_TASKS=spec SPEC_OPTS="--tag content"
  - RAKE_TASKS=spec SPEC_OPTS="--tag ~content"

matrix:
  fast_finish: true
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - rake --version
  # Fail build if msftidy is not successful
  - ln -sf ../../tools/dev/pre-commit-hook.rb ./.git/hooks/post-merge
  - ls -la ./.git/hooks
  - ./.git/hooks/post-merge
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake --version
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  # fail build if db/schema.rb update is not committed
  - git diff --exit-code db/schema.rb && bundle exec rake $RAKE_TASKS

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 5

# Blacklist certain branches from triggering travis builds
branches:
  except:
    - gh-pages
    - metakitty
