apiVersion: v1
kind: Service
metadata:
  name: {{ include "metasploit.fullname" . }}
  labels:
    {{- include "metasploit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metasploit
      protocol: TCP
      name: http
  selector:
    {{- include "metasploit.selectorLabels" . | nindent 4 }}
