# Additionally influences open graph metadata as part of jekyll-seo-tag, and the theme
title: 'Metasploit Documentation | Penetration Testing Software, Pen Testing Security'
description: View Metasploit Framework Documentation
searchTitle: Metasploit Documentation
baseurl: ''
url: 'https://rapid7.github.io/metasploit-framework'
logo: assets/images/favicon.png

# Build settings
theme: just-the-docs
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: development

exclude:
  - '*.rb'
  - 'build.rb'
  - metasploit-framework.wiki
  - metasploit-framework.wiki.old
  - README.md

# just-the-docs config
mermaid_enabled: true
mermaid:
  version: "9.2.2"
heading_anchors: true
aux_links_new_tab: true
aux_links:
  'Metasploit Framework on GitHub':
    - '//github.com/rapid7/metasploit-framework'

nav_cache: true

# We set gh_edit_link to false to opt out of the default edit link support - and instead use a custom implementation in _includes/footer_custom.html
gh_edit_link: false
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/rapid7/metasploit-framework'
gh_edit_branch: 'master'
gh_edit_source: docs
gh_edit_view_mode: 'tree'

ga_tracking: UA-4622520-7
ga_tracking_anonymize_ip: true

favicon: assets/images/favicon.png

back_to_top: true
back_to_top_text: 'Back to top'

just_the_docs:
  collections: []

ignore_theme_config: true
